chatbot/urls.py
from django.conf.urls import url

from . import views



urlpatterns = [
	url(r'^chat/$', views.Chat, name='chat'),
	url(r'^chat/create', views.CrearConversacion, name='create-chat'),
	url(r'^chat/get$', views.ObtenerConversacion, name='get-chat'),
]

eventos/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^articulos/$', views.ArticulosListView.as_view(), name='articulos'),
	url(r'^eventos/$', views.EventosListView.as_view(), name='eventos'),
	url(r'^proyectos/$', views.ProyectosListView.as_view(), name='proyectos'),
]

lixbotchat/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

urlpatterns = [

]

from django.urls import include

urlpatterns += [
    path('', include('eventos.urls')),
    path('', include('chatbot.urls'))
]

# #Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/eventos/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articulos/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class articulos(models.Model):
    
	nombre=models.CharField(max_length=50)
	tipo=models.CharField(max_length=50)
	costo=models.CharField(max_length=50)
	descripcion=models.CharField(max_length=50,default="")
	fecha_lanzamiento=models.DateTimeField(default=now)
	descuento=models.BooleanField()
	procentaje_descuento=models.BigIntegerField()
	urlFoto=models.CharField(max_length=50)


	def __str__(self):
    		return  '%s %s' % (self.nombre,self.tipo)

    

eventos/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class evento(models.Model):
    
    titulo=models.CharField(max_length=50)
    proposito=models.CharField(max_length=50)
    fecha_realizacion=models.DateTimeField(default=now)
    descripcion=models.CharField(max_length=50)
    urlFoto=models.CharField(max_length=50)
	
    def __str__(self):
    
    		return  '%s %s' % (self.titulo,self.fecha_realizacion)
    


	
    

proyectos/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class proyectos(models.Model):
    
    titulo=models.CharField(max_length=50)
    proposito=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=50)
    urlFoto=models.CharField(max_length=50)
	

    def __str__(self):
    
    		return  '%s %s' % (self.nombre,self.proposito)

articulos/views.py
from django.shortcuts import render

# Create your views here.

eventos/views.py
from django.shortcuts import render

from articulos.models import articulos
from eventos.models import evento
from proyectos.models import proyectos

# Create your views here.
def index(request):
    """
    Función vista para la página inicio del sitio.
    """
    return render(
        request,
        'index.html'
    )


from django.views import generic

class ArticulosListView(generic.ListView):
    model = articulos
    paginate_by = 10
    template_name = 'articulos.html'
    def get_context_data(self, **kwargs):
        context = super(ArticulosListView, self).get_context_data(**kwargs)
        lista_articulos= articulos.objects.values()
        print(str(lista_articulos))
        context['lista_articulos'] = lista_articulos
        return context

class EventosListView(generic.ListView):
    model = evento
    paginate_by = 10
    template_name = 'eventos.html'

    def get_context_data(self, **kwargs):
        context = super(EventosListView, self).get_context_data(**kwargs)
        lista_eventos= evento.objects.values()
        print(str(lista_eventos))
        context['lista_evento'] = lista_eventos
        return context

class ProyectosListView(generic.ListView):
    
    model = proyectos
    paginate_by = 10
    template_name = 'proyectos.html'  

    def get_context_data(self, **kwargs):
        context = super(ProyectosListView, self).get_context_data(**kwargs)
        lista_proyectos= proyectos.objects.values()
        print(str(lista_proyectos))
        context['lista_proyectos'] = lista_proyectos
        return context

proyectos/views.py
from django.shortcuts import render

# Create your views here.

templates/articulos.html
{% extends 'template.html' %}
{% load static %}
{% block title %}<title>Articulos</title>{% endblock %}
{% block content %}
<div class="parallax-background">
    <img class="parallax-background-image" src="{% static 'img/template/bl.jpg'%}">
</div>

<div class= "container">     
        <div class="row">
            <div class="col-md-5 hidden-xs" >
                
            </div>
            <div class="col-md-4 col-md-offset-1">
                <div class="description" style="align-content:right;">
                    <h2><img class="parallax-background-image" src="{% static 'img/logos/logo_lix_bot_lt.png'%}"></h2>
                    <h4  style="position:absolute; color:#00BFFF;">ARTICULOS</h4>
                </div>

            </div>
        </div>
        
    </div>
</div>
<div>
    {% if lista_articulos %}

    {% for articulo in lista_articulos %}
    <div class="section section-features">
        <div class="container">
            <h4 class="header-text text-center">{{articulo.nombre}}</h4>
            <div class="row">
                <div class="col-md-8" style="display: inline-block;">
                    <img src="/media/{{articulo.urlFoto}} " alt="" width="500" height="300">
                </div>
                <div class="col-md-4">
                    <p>
                        {{articulo.descripcion}}
                     </p>
                    <p>
                       Tipo Producto: {{articulo.tipo}}
                    </p>
                    <p>
                       Precio: {{articulo.costo}}
                    </p>
                    {% if articulo.descuento %}
                    <h6>PRODUCTO EN DESCUENTO</h6>
                    <p>
                        
                        Descuento: {{articulo.procentaje_descuento}}%
                    </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>

{% endblock %}

templates/eventos.html
{% extends 'template.html' %}
{% load static %}
{% block title %}<title>Eventos</title>{% endblock %}
{% block content %}
<div class="parallax-background">
    <img class="parallax-background-image" src="{% static 'img/template/bl.jpg'%}">
</div>

<div class= "container">     
        <div class="row">
            <div class="col-md-5 hidden-xs" >
                
            </div>
            <div class="col-md-4 col-md-offset-1">
                <div class="description" style="align-content:right;">
                    <h2><img class="parallax-background-image" src="{% static 'img/logos/logo_lix_bot_lt.png'%}"></h2>
                    <h4  style="position:absolute; color:#00BFFF;">EVENTOS</h4>
                </div>

            </div>
        </div>
        
    </div>
</div>
<div>
    {% if evento_list %}

    {% for evento in lista_evento %}
    <div class="section section-features">
        <div class="container">
            <h4 class="header-text text-center">{{evento.titulo}}</h4>
            <div class="row">
                <div class="col-md-8" style="display: inline-block;">
                    <img src="/media/{{evento.urlFoto}} " alt="" width="500" height="300">
                </div>
                <div class="col-md-4">
                    <p>
                        {{evento.descripcion}}
                    </p>
                    <br>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>

{% endblock %}

templates/index.html
{% extends 'template.html' %}
{% load static %}
{% block content %}

<div class="parallax-background">
    <img class="parallax-background-image" src="{% static 'img/template/bl.jpg'%}">
</div>
          
<div class= "container">     
        <div class="row">
            <div class="col-md-5 hidden-xs" >
                
            </div>
            <div class="col-md-6 col-md-offset-1">
                <div class="description" >
                    <h2><img class="parallax-background-image" src="{% static 'img/logos/logo_lix_bot_lt.png'%}"></h2>

                    <h5  style="position:absolute;  left:5;">En cada época de la humanidad ha habido una tecnología imperante. Desde la prehistoria hasta la actualidad la tecnología se ha ido perfeccionando de manera gradual.</h5>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="section section-gray section-clients">
    <div class="container text-center">
        <h4 class="header-text1">EL GRAN MOTOR DE LA TECNOLOGÍA</h4>
        <p class="style1">
            El destino del ser humano es incrementar sus capacidades como cyborgs (combinación de partes orgánicas y electrónicas), gracias a los tantos dispositivos tecnológicos que ya ofrece la ciencia <br>
        </p>
        
        <div class="logos">
            <ul class="list-unstyled">
                <li ><img src="{% static 'img/logos/cisco.png'%}"/></li>
                <li ><img src="{% static 'img/logos/kali.png'%}"/></li>
                <li ><img src="{% static 'img/logos/tp.png'%}"/></i>
                <li ><img src="{% static 'img/logos/n.png'%}"/></li>
                <li ><img src="{% static 'img/logos/u.png'%}"/></li>
                <li ><img src="{% static 'img/logos/w.png'%}"/></li>
            </ul>
        </div>
    </div>
</div>
<div class="section section-presentation">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="description">
                    <h4 class="header-text">EL FUTURO</h4>
                    <p>La inteligencia artificial hace posible que los robots aprendan de la experiencia, se ajusten a nuevas aportaciones y realicen tareas como hacen los humanos, como por ejemplo computadoras que juegan ajedrez hasta automóviles que se conducen por sí solos, se sustentan mayormente en aprendizaje a fondo y procesamiento del lenguaje natural. Mediante el uso de estas tecnologías, los robots pueden ser entrenados para realizar tareas específicas procesando grandes cantidades de datos y reconociendo patrones en los datos. </p>
                    
                    <p>
                </div>
            </div>
            <div class="col-md-5 col-md-offset-1 hidden-xs">
                <img src="{% static 'img/template/mac.png'%}"/>
            </div>
        </div>
    </div>
</div>
<div class="section section-demo">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div id="description-carousel" class="carousel fade" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="item">
                            <img src="{% static 'img/template/examples/home_33.jpg'%}" alt="">
                        </div>
                        <div class="item active">
                            <img src="{% static 'img/template/examples/home_22.jpg'%}" alt="">
                        </div>
                        <div class="item">
                            <img src="{% static 'img/template/examples/home_11.jpg'%}" alt="">
                        </div>
                    </div>
                    <ol class="carousel-indicators carousel-indicators-blue">
                        <li data-target="#description-carousel" data-slide-to="0" class=""></li>
                        <li data-target="#description-carousel" data-slide-to="1" class="active"></li>
                        <li data-target="#description-carousel" data-slide-to="2" class=""></li>
                    </ol>
                </div>
            </div>
            <div class="col-md-5 col-md-offset-1">
                <h4 class="header-text2">HOY TE TRAEMOS AL ROBOT BAMBI</h4>
                <p>
                    Bambi es un robot amigable que te acompañara a realizar tus actividades diarias como: cantar, bailar, hacer ejercicio y todo tipo de tareas que le puedes programar ¿Qué estas esperando para compartir momentos agradables con este compañero?
                </p>
                
            </div>
        </div>
    </div>
</div>
<div class="section section-features">
    <div class="container">
        <h4 class="header-text text-center">FUNCIONES</h4>
        <div class="row">
            <div class="col-md-4">
                <div class="card card-blue">
                        <div class="icon">  
                        

                        <!-- <i class="pe-7s-note2"></i>-->
                        <img src="{% static 'img/logos/archivo.png'%}"/> </i>
                        
                    </div>
                    <div class="text">
                        <h4>Comparte Archivos</h4>
                        <p>Puedes consultar informacion de cualquier tipo, Bambi se encargara de ayudarte con esas dificiles investigaciones y trabajos que envian los profesores </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-blue">
                    <div class="icon">
                        <!-- <i class="pe-7s-bell"></i>-->
                        <img src="{% static 'img/logos/mensaje.png'%}"/> </i>
                    </div>
                    <h4>Mensaje</h4>
                    <p>Puedes programarlo para que hable cualquier idioma, puedes conversar con Bambi el lenguaje que prefieras</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-blue">
                    <div class="icon">
                        <!--<i class="pe-7s-graph1"></i>-->
                        <img src="{% static 'img/logos/musica.png'%}"/> </i>
                    </div>
                    <h4>Musica</h4>
                    <p>Puede bailar cualquier tipo de coreografia, solo tienes que buscarla, Bambi tiene pasos excelentes</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section section-testimonial">
    <div class="container">
        <h4 class="header-text text-center">Lo que la gente piensa</h4>
        <div id="carousel-example-generic" class="carousel fade" data-ride="carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner " role="listbox">
                <div class="item">
                    <div class="mask">
                        <img src="{% static 'img/faces/face-4.jpg'%}">
                    </div>
                    <div class="carousel-testimonial-caption">
                        <p style="text-align: center">Stefanny Rodriguez</p>
                        <h3>Excelentes aportes a las tendencias tecnologicas</h3>
                    </div>
                </div>
                <div class="item active">
                    <div class="mask">
                        <img src="{% static 'img/faces/face-3.jpg'%}">
                    </div>
                    <div class="carousel-testimonial-caption">
                        <p style="text-align: center">Juan Perez</p>
                        <h3>Que buenos proyecto se encuentras propuestos</h3>
                    </div>
                </div>
                <div class="item">
                    <div class="mask">
                        <img src="{% static 'img/faces/face-2.jpg'%}">
                    </div>
                    <div class="carousel-testimonial-caption">
                        <p style="text-align: center">John Min Ho</p>
                        <h3>Grandiosos los avances tencologicos que manejan</h3>
                    </div>
                </div>
            </div>
            <ol class="carousel-indicators carousel-indicators-blue">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
        </div>
    </div>
</div>
<div class="section section-no-padding">
    <div class="parallax filter-gradient blue" data-color="blue">
        <div class="parallax-background">
            <img class ="parallax-background-image" src="{% static 'img/template/bg3.jpg'%}"/>
        </div>
        <div class="info"> <!-- CAMBIAR EL LINK (NO OLVIDAR) -->
            <a href="http://www.creative-tim.com/product/awesome-landing-page" class="btn btn-neutral btn-lg btn-fill">CONTÁCTANOS</a>
        </div>
    </div>
</div>
{% endblock %}

templates/proyectos.html
{% extends 'template.html' %}
{% load static %}
{% block title %}<title>Proyectos</title>{% endblock %}
{% block content %}
<div class="parallax-background">
    <img class="parallax-background-image" src="{% static 'img/template/bl.jpg'%}">
</div>

<div class= "container">     
        <div class="row">
            <div class="col-md-5 hidden-xs" >
                
            </div>
            <div class="col-md-4 col-md-offset-1">
                <div class="description" style="align-content:right;">
                    <h2><img class="parallax-background-image" src="{% static 'img/logos/logo_lix_bot_lt.png'%}"></h2>
                    <h4  style="position:absolute; color:#00BFFF;">PROYECTOS</h4>
                </div>

            </div>
        </div>
        
    </div>
</div>
<div>
    {% if lista_proyectos %}

    {% for proyecto in lista_proyectos %}
    <div class="section section-features">
        <div class="container">
            <h4 class="header-text text-center">{{proyecto.titulo}}</h4>
            <div class="row">
                <div class="col-md-8" style="display: inline-block;">
                    <img src="/media/{{proyecto.urlFoto}} " alt="" width="500" height="300">
                </div>
                <div class="col-md-4">
                    <p>
                        {{proyecto.descripcion}}
                    </p>
                    <br>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>

{% endblock %}

templates/template.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />
        {% block title %}<title>LIX BOX</title>{% endblock %}
        <link rel="icon" href="{%static 'img/icono.ico' %}">
        <!-- 
        <link href="assets/css/bootstrap.css" rel="stylesheet" />
        <link href="assets/css/landing-page.css" rel="stylesheet"/>-->
        
        <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
        <link rel="stylesheet" href="{% static 'css/landing-page.css' %}">

        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300' rel='stylesheet' type='text/css'>
       
       <!-- <link href="assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
        <link href="assets/css/nav-bar.css" rel="stylesheet" />-->

        <link rel="stylesheet" href="{% static 'css/pe-icon-7-stroke.css'%}">
        <link rel="stylesheet" href="{% static 'css/nav-bar.css' %}">

          <!--<link rel="stylesheet" href="assets/css/chat/styles-merged.css">
          <link rel="stylesheet" href="assets/css/chat/styles_chat.css">
          <link rel="stylesheet" href="assets/css/chat/style.min.css">
          <link rel="stylesheet" href="assets/css/chat/custom.css">-->

        <link rel="stylesheet" href="{% static 'css/chat/styles-merged.css'%}">
        <link rel="stylesheet" href="{% static 'css/chat/style.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/chat/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/chat/styles_chat.css' %}">

    </head>
    <body class="landing-page landing-page1">
        <div>
        <nav class="navbar navbar-default banner">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'index' %}" style="color: #00BFFF">LIX BOX</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    
                    <ul class="nav navbar-nav navbar-right navbar-nav-primary">
                        <li><a href="{% url 'index' %}" style="color: #00BFFF">Home</a></li>
                        <li><a href="{% url 'proyectos' %}" style="color: #00BFFF">PROYECTOS</a></li>
                        <li><a href="{% url 'articulos' %}" style="color: #00BFFF">ARTICULOS</a></li>
                        <li><a href="{% url 'eventos' %}" style="color: #00BFFF">EVENTOS</a></li>
                    </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
            </div>
            <div class="parallax filter-gradient blue" data-color="blue">
                
            


                {% block content %}{% endblock %}

                
            </div>
            <div>
                <footer class="footer">
                    <div class="container">
    
                        <div class="copyright">
                            &copy; 2020 </a>LIXBOT
                        </div>
                    </div>
                </footer>
            </div>
            
            <div class="chat">
                <audio id="tono" src="{% static 'audio/tono.mp3' %}" preload="auto">
                </audio>
                <p class="title-chat">Preguntanos</p>
                <div class="box-chat">
                <div class="ocultar-chat" style="display: none;">
                    <div class="body-chat">
                    </div>
                    <form id="chat-form" method="post" data-post-url="{% url 'chat' %}" data-post-get-url="{% url 'get-chat' %}" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-chat">
                        <input type="hidden" name="token" value="">
                        <textarea type="text" class="input-mensaje" Placeholder="Escribe un mensaje" name="mensaje"></textarea>
                        <button type="submit" style="background:#1E90FF" class="btn btn-primary button-send" Placeholder="Escribe un mensaje">Enviar</button>
                    </div>
                    </form>
                </div>
                <div class="create-chat">
                    <form id="create-chat-form" method="post" data-post-url="{% url 'create-chat' %}" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-new-chat">
                        <div class="row text-center">
                        <p>Hola, por favor rellena la siguiente informacion:</p>
                        </div>
                        <div class="row text-center inputs-new-chat">
                        <label for="nombre" class="col-form-label sm-2">Nombre</label>
                        <input type="text" required class="col-form sm-10 create-chat-nombre" placeholder="Maria Perez" name="nombre">
                        <label for="correo" class="col-form-label sm-2">Correo</label>
                        <input type="email" required="" class="create-chat-correo" placeholder="ejemplo@mail.com" name="correo">
                        </div>
                        <div class="row text-center">
                        <button type="submit" class="btn btn-info button-create-chat">Iniciar chat</button>
                        </div>
                    </div>
                    </form>
                </div>

            </div>



    </body>
    <!--<script src="assets/js/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="assets/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
    <script src="assets/js/bootstrap.js" type="text/javascript"></script>
    <script src="assets/js/awesome-landing-page.js" type="text/javascript"></script>

    <script src="assets/js/chat/scripts.min.js"></script>
    <script src="assets/js/chat/main.min.js"></script>
    <script src="assets/js/chat/custom.js"></script>
    <script src="assets/js/chat/jquery.cookie.js"></script>
    <script src="assets/js/chat/chat.js"></script>-->

    <script src="{% static 'js/jquery-1.10.2.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/awesome-landing-page.js' %}" type="text/javascript"></script>

    <script src="{% static 'js/chat/scripts.min.js' %}"></script>
    <script src="{% static 'js/chat/main.min.js' %}"></script>
    <script src="{% static 'js/chat/custom.js' %}"></script>
    <script src="{% static 'js/chat/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/chat/chat.js' %}"></script>    
    <script src="{% static 'js/nav-bar.js' %}"></script>


</html>